version: 1
formats: []

build:
  image: latest

sphinx:
  configuration: docs/conf.py
  fail_on_warning: false
  builder: html

submodules:
  include: all
  recursive: true



python:
  version: "3.8"
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs