name: aiowowapi Tests

on:
  - push
  - pull_request

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version: ['3.8', '3.9', '3.10']

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest mypy pytest-asyncio
        pip install -e .
    - name: Lint with flake8
      run: |
        flake8 ./src --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 ./src --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics --ignore F401,F403,E501,F541
    - name: Validate types with mypy
      run: |
        mypy ./src --no-strict-optional
    - name: Test with pytest
      run: |
        pytest ./tests
